### ISSUE TITLE
Show PI on user management page

### ISSUE THREAD

**Issue by umass-jgriffin** [UnityHPC/account-portal#54] opened 2023-03-07 18:50 UTC
Right now PI's and users are managed on separate pages.  It would be nice if the user management page had a way of indicating what PI group(s) a user is a member of.

**Comment by hakasapl** [comment] 2023-03-07 18:52
Duplicate of https://github.com/UnityHPC/unity-web-portal/issues/29, which has since closed and will be included in the next release (this Friday hopefully!)

**Closed by hakasapl** 2023-03-07 18:52 UTC
Labels: feature

**Comment by umass-jgriffin** [comment] 2023-03-07 18:55
Ah, that's why I didn't see it already! Thanks!
